import{loginWithGoogle,logout,watchAuth}from"./auth.js";import{loadCompanySettings,saveCompanySettings,uploadCompanyImage,deleteCompanyImage}from"./company.js";import{calculateInvoiceGST,GST_RATES}from"./gst.js";import{buildInvoiceHTML,renderInvoicePreview}from"./invoice.js";import{generateInvoicePDF}from"./pdf.js";
const $=id=>document.getElementById(id),S=["Andhra Pradesh","Arunachal Pradesh","Assam","Bihar","Chhattisgarh","Goa","Gujarat","Haryana","Himachal Pradesh","Jharkhand","Karnataka","Kerala","Madhya Pradesh","Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Odisha","Punjab","Rajasthan","Sikkim","Tamil Nadu","Telangana","Tripura","Uttar Pradesh","Uttarakhand","West Bengal","Delhi","Jammu and Kashmir","Ladakh","Puducherry","Chandigarh","Andaman and Nicobar Islands","Lakshadweep","Dadra and Nagar Haveli and Daman and Diu"];
const st={uid:null,company:{},items:[],id:1,seller:{},buyer:{},invoiceNumber:"",invoiceDate:"",placeOfSupply:"",notes:""};const money=v=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(Number(v)||0),esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
function toast(x,type="success"){let t=document.createElement("div");t.className="toast "+type;t.textContent=x;$("toastContainer").appendChild(t);setTimeout(()=>t.remove(),2800)}
function opts(id){$(id).innerHTML='<option value="">Select state</option>'+S.map(x=>`<option>${esc(x)}</option>`).join("")}
function init(){["companyState","sellerState","buyerState","placeOfSupply"].forEach(opts);st.invoiceNumber=`INV-${String(Number(localStorage.getItem("gstBillInvoiceCounter")||1)).padStart(4,"0")}`;st.invoiceDate=new Date().toISOString().slice(0,10);$("invoiceNumber").value=st.invoiceNumber;$("invoiceDate").value=st.invoiceDate;add();bind()}
function add(){st.items.push({id:st.id++,name:"",hsn:"",qty:1,rate:0,gst:18});render();update()}
function render(){let b=$("itemsBody");b.innerHTML="";st.items.forEach((x,i)=>{let r=document.createElement("tr");r.dataset.id=x.id;r.innerHTML=`<td>${i+1}</td><td><input class="input" data-f="name" value="${esc(x.name)}"></td><td><input class="input" data-f="hsn" value="${esc(x.hsn)}"></td><td><input class="input" type="number" data-f="qty" value="${x.qty}"></td><td><input class="input" type="number" data-f="rate" value="${x.rate}"></td><td><select class="input" data-f="gst">${GST_RATES.map(g=>`<option ${g==x.gst?"selected":""}>${g}</option>`).join("")}</select></td><td class="amt">${money(x.qty*x.rate)}</td><td><button class="item-delete-btn" data-del="${x.id}">×</button></td>`;b.appendChild(r)})}
function sync(){st.invoiceNumber=$("invoiceNumber").value;st.invoiceDate=$("invoiceDate").value;st.placeOfSupply=$("placeOfSupply").value;st.seller={name:$("sellerName").value,address:$("sellerAddress").value,gstin:$("sellerGSTIN").value,state:$("sellerState").value};st.buyer={name:$("buyerName").value,address:$("buyerAddress").value,gstin:$("buyerGSTIN").value,state:$("buyerState").value};st.notes=$("invoiceNotes").value}
function calc(){sync();return calculateInvoiceGST({items:st.items,sellerState:st.seller.state,buyerState:st.buyer.state})}
function update(){let r=calc();["taxableAmount","cgstAmount","sgstAmount","igstAmount"].forEach((id,i)=>$(id).textContent=money([r.taxableAmount,r.cgst,r.sgst,r.igst][i]));$("grandTotal").textContent=money(r.grandTotal);$("taxModeMessage").textContent=!st.seller.state||!st.buyer.state?"Select Seller and Buyer State.":r.isSameState?"Same-state: CGST + SGST.":"Inter-state: IGST."}
function companyRead(){st.company={name:$("companyName").value,address:$("companyAddress").value,gstin:$("companyGSTIN").value.toUpperCase().replace(/\s/g,""),state:$("companyState").value,phone:$("companyPhone").value,email:$("companyEmail").value,upiId:$("upiId").value,accountHolder:$("accountHolder").value,bankName:$("bankName").value,accountNumber:$("accountNumber").value,ifsc:$("ifsc").value.toUpperCase().replace(/\s/g,""),branch:$("branch").value,paymentNotes:$("paymentNotes").value,...st.company}}
function companyApply(){let c=st.company;const map={companyName:"name",companyAddress:"address",companyGSTIN:"gstin",companyState:"state",companyPhone:"phone",companyEmail:"email",upiId:"upiId",accountHolder:"accountHolder",bankName:"bankName",accountNumber:"accountNumber",ifsc:"ifsc",branch:"branch",paymentNotes:"paymentNotes"};Object.entries(map).forEach(([a,b])=>$(a).value=c[b]||"");["logoPreview","qrPreview"].forEach((id,i)=>{let u=i?c.qrUrl:c.logoUrl;$(id).innerHTML=u?`<img src="${esc(u)}">`:i?"No QR":"No logo"})}
async function save(){companyRead();await saveCompanySettings(st.uid,st.company);toast("Settings saved")}
async function upload(type){let f=$(type+"File").files[0];if(!f)return;try{let u=await uploadCompanyImage(st.uid,f,type);st.company[type==="logo"?"logoUrl":"qrUrl"]=u;await save();companyApply();toast("Image uploaded")}catch(e){toast(e.message,"error")}}
async function remove(type){await deleteCompanyImage(st.uid,type);delete st.company[type==="logo"?"logoUrl":"qrUrl"];await save();companyApply();toast("Image removed")}
function data(){let r=calc();return{invoiceNumber:st.invoiceNumber,invoiceDate:st.invoiceDate,placeOfSupply:st.placeOfSupply,seller:st.seller,buyer:st.buyer,items:r.calculatedItems,result:r,notes:st.notes,company:st.company}}
function bind(){ $("loginBtn").onclick=$("loginBtnMain").onclick=async()=>{try{await loginWithGoogle()}catch(e){$("authMessage").textContent=e.message}};$("logoutBtn").onclick=logout;$("saveSettingsBtn").onclick=save;$("logoFile").onchange=()=>upload("logo");$("qrFile").onchange=()=>upload("qr");$("removeLogoBtn").onclick=()=>remove("logo");$("removeQrBtn").onclick=()=>remove("qr");$("resetSettingsBtn").onclick=async()=>{if(confirm("Reset settings?")){st.company={};await save();companyApply()}};$("addItemBtn").onclick=add;$("itemsBody").onclick=e=>{let b=e.target.closest("[data-del]");if(!b)return;if(st.items.length===1)return toast("At least one item is required","warning");st.items=st.items.filter(x=>x.id!=b.dataset.del);render();update()};$("itemsBody").oninput=e=>{let r=e.target.closest("tr"),x=st.items.find(a=>a.id==r.dataset.id);if(!x)return;x[e.target.dataset.f]=["qty","rate","gst"].includes(e.target.dataset.f)?Number(e.target.value)||0:e.target.value;r.querySelector(".amt").textContent=money(x.qty*x.rate);update()};document.addEventListener("input",e=>{if(!e.target.closest("#itemsBody"))update()});document.addEventListener("change",e=>{if(!e.target.closest("#itemsBody"))update()});$("previewInvoiceBtn").onclick=()=>{ $("invoicePreviewModal").classList.remove("hidden");renderInvoicePreview($("invoicePreviewContainer"),data())};$("closePreviewBtn").onclick=()=>$("invoicePreviewModal").classList.add("hidden");$("downloadPdfBtn").onclick=async()=>{try{await generateInvoicePDF({html:buildInvoiceHTML(data()),invoiceNumber:st.invoiceNumber});toast("PDF downloaded")}catch(e){toast(e.message,"error")}};$("clearInvoiceBtn").onclick=()=>{location.reload()}}
watchAuth(async u=>{if(u){st.uid=u.uid;$("loginCard").classList.add("hidden");$("app").classList.remove("hidden");$("loginBtn").classList.add("hidden");$("loginBtnMain").classList.add("hidden");$("logoutBtn").classList.remove("hidden");$("userEmail").textContent=u.email||"";st.company=await loadCompanySettings(u.uid);companyApply()}else{$("loginCard").classList.remove("hidden");$("app").classList.add("hidden");$("loginBtn").classList.remove("hidden");$("loginBtnMain").classList.remove("hidden");$("logoutBtn").classList.add("hidden")}});init();
