const GST_RATES=[0,5,12,18,28];
const STATES=["Andhra Pradesh","Arunachal Pradesh","Assam","Bihar","Chhattisgarh","Goa","Gujarat","Haryana","Himachal Pradesh","Jharkhand","Karnataka","Kerala","Madhya Pradesh","Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Odisha","Punjab","Rajasthan","Sikkim","Tamil Nadu","Telangana","Tripura","Uttar Pradesh","Uttarakhand","West Bengal","Andaman and Nicobar Islands","Chandigarh","Dadra and Nagar Haveli and Daman and Diu","Delhi","Jammu and Kashmir","Ladakh","Lakshadweep","Puducherry"];
const state={items:[],nextId:1,logo:"",qr:"",signature:""};
const $=id=>document.getElementById(id);
const money=v=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",minimumFractionDigits:2}).format(Number(v)||0);
const round=v=>Math.round((Number(v)||0)*100)/100;
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const safe=(v,f="—")=>{const s=String(v??"").trim();return s?esc(s):f};
function today(){const d=new Date(),x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)}
function init(){
 ["sellerState","buyerState","placeOfSupply"].forEach(id=>$(id).innerHTML='<option value="">Select state</option>'+STATES.map(s=>`<option>${esc(s)}</option>`).join(""));
 $("invoiceDate").value=today();addItem();bind();update();
}
function addItem(){state.items.push({id:state.nextId++,name:"",hsn:"",qty:1,rate:0,gst:18});renderItems();update()}
function renderItems(){
 $("itemsBody").innerHTML=state.items.map((x,i)=>`<tr data-id="${x.id}" class="border-b">
<td class="p-2">${i+1}</td><td class="p-2"><input data-field="name" value="${esc(x.name)}" class="w-full rounded-lg border px-2 py-2"></td>
<td class="p-2"><input data-field="hsn" value="${esc(x.hsn)}" class="w-full rounded-lg border px-2 py-2"></td>
<td class="p-2"><input data-field="qty" type="number" min="0" step=".01" value="${x.qty}" class="w-24 rounded-lg border px-2 py-2"></td>
<td class="p-2"><input data-field="rate" type="number" min="0" step=".01" value="${x.rate}" class="w-28 rounded-lg border px-2 py-2"></td>
<td class="p-2"><select data-field="gst" class="rounded-lg border px-2 py-2">${GST_RATES.map(r=>`<option value="${r}" ${r===x.gst?"selected":""}>${r}%</option>`).join("")}</select></td>
<td class="p-2 font-bold">${money(round(x.qty*x.rate))}</td><td class="p-2"><button data-delete="${x.id}" class="rounded-lg border px-2 py-1 text-red-600">×</button></td></tr>`).join("");
}
function calculate(){
 const seller=$("sellerState").value,buyer=$("buyerState").value,same=!!seller&&seller===buyer,inter=!!seller&&!!buyer&&seller!==buyer;
 let taxable=0,cgst=0,sgst=0,igst=0;
 const items=state.items.map(x=>{const qty=Math.max(0,Number(x.qty)||0),rate=Math.max(0,Number(x.rate)||0),gstRate=Math.max(0,Number(x.gst)||0),t=round(qty*rate),g=round(t*gstRate/100);let c=0,s=0,i=0;if(same){c=round(g/2);s=round(g-c)}else if(inter)i=g;taxable+=t;cgst+=c;sgst+=s;igst+=i;return {...x,qty,rate,gstRate,taxableAmount:t,gstAmount:g,cgst:c,sgst:s,igst:i,total:round(t+g)}});
 cgst=round(cgst);sgst=round(sgst);igst=round(igst);return{items,taxable:round(taxable),cgst,sgst,igst,totalGST:round(cgst+sgst+igst),grand:round(taxable+cgst+sgst+igst),same,inter}
}
function collect(){const r=calculate(),v=id=>$(id).value||"";return{invoiceNumber:v("invoiceNumber"),invoiceDate:v("invoiceDate"),dueDate:v("dueDate"),paymentTerms:v("paymentTerms"),placeOfSupply:v("placeOfSupply"),seller:{name:v("sellerName"),gstin:v("sellerGSTIN"),phone:v("sellerPhone"),email:v("sellerEmail"),state:v("sellerState"),address:v("sellerAddress")},buyer:{name:v("buyerName"),gstin:v("buyerGSTIN"),phone:v("buyerPhone"),email:v("buyerEmail"),state:v("buyerState"),address:v("buyerAddress")},items:r.items,result:r,notes:v("invoiceNotes"),signatoryName:v("signatoryName"),upiId:v("upiId"),accountName:v("accountName"),bankName:v("bankName"),accountNumber:v("accountNumber"),ifsc:v("ifsc"),paymentNote:v("paymentNote"),logo:state.logo,qr:state.qr,signature:state.signature}}
function update(){const r=calculate();$("taxableTotal").textContent=money(r.taxable);$("cgstTotal").textContent=money(r.cgst);$("sgstTotal").textContent=money(r.sgst);$("igstTotal").textContent=money(r.igst);$("grandTotal").textContent=money(r.grand);$("taxMode").textContent=r.same?"Same-state: CGST + SGST":r.inter?"Inter-state: IGST":"Select seller and buyer states."}
function fileToData(input,key,thumb){const f=input.files?.[0];if(!f)return;if(f.size>3*1024*1024){alert("Please use an image smaller than 3 MB.");input.value="";return}const r=new FileReader();r.onload=()=>{state[key]=r.result;$(thumb).src=r.result;$(thumb).classList.remove("hidden")};r.readAsDataURL(f)}
function bind(){
 $("addItemBtn").onclick=addItem;$("previewBtn").onclick=showPreview;$("downloadBtn").onclick=downloadPDF;$("closePreview").onclick=closePreview;$("resetBtn").onclick=resetAll;
 document.addEventListener("input",e=>{if(e.target.closest("main"))update()});
 document.addEventListener("change",e=>{if(e.target.id==="logoInput")fileToData(e.target,"logo","logoThumb");if(e.target.id==="upiQrInput")fileToData(e.target,"qr","upiQrThumb");if(e.target.id==="signatureInput")fileToData(e.target,"signature","signatureThumb");update()});
 $("itemsBody").addEventListener("input",e=>{const row=e.target.closest("tr"),item=state.items.find(x=>x.id===Number(row?.dataset.id));if(!item)return;const f=e.target.dataset.field;item[f]=(f==="name"||f==="hsn")?e.target.value:Number(e.target.value)||0;renderItems();update()});
 $("itemsBody").addEventListener("change",e=>{const row=e.target.closest("tr"),item=state.items.find(x=>x.id===Number(row?.dataset.id));if(!item)return;item[e.target.dataset.field]=Number(e.target.value)||0;renderItems();update()});
 $("itemsBody").addEventListener("click",e=>{const b=e.target.closest("[data-delete]");if(!b)return;state.items=state.items.filter(x=>x.id!==Number(b.dataset.delete));if(!state.items.length)addItem();else{renderItems();update()}});
}
function invoiceHTML(d){
 const r=d.result,rows=d.items.map((x,i)=>`<tr><td>${i+1}</td><td><b>${safe(x.name,"Product / Service")}</b></td><td>${safe(x.hsn)}</td><td class="r">${x.qty}</td><td class="r">${money(x.rate)}</td><td class="r">${money(x.taxableAmount)}</td><td class="r">${x.gstRate}%</td><td class="r b">${money(x.total)}</td></tr>`).join("");
 const payment=(d.upiId||d.accountName||d.bankName||d.accountNumber||d.ifsc||d.qr)?`<div class="payment section"><div><div class="label">PAYMENT DETAILS</div>${d.upiId?`<div><b>UPI ID:</b> ${safe(d.upiId)}</div>`:""}${d.accountName?`<div><b>Account Holder:</b> ${safe(d.accountName)}</div>`:""}${d.bankName?`<div><b>Bank:</b> ${safe(d.bankName)}</div>`:""}${d.accountNumber?`<div><b>Account No:</b> ${safe(d.accountNumber)}</div>`:""}${d.ifsc?`<div><b>IFSC:</b> ${safe(d.ifsc)}</div>`:""}${d.paymentNote?`<div class="muted">${safe(d.paymentNote)}</div>`:""}</div>${d.qr?`<div class="qrwrap"><img src="${d.qr}" class="qr"><div class="qrtext">UPI / Scan to Pay</div></div>`:""}</div>`:"";
 return `<!doctype html><html><head><meta charset="utf-8"><style>
*{box-sizing:border-box}body{margin:0;background:#fff;color:#172033;font-family:Arial,Helvetica,sans-serif;font-size:9px}.page{width:210mm;min-height:297mm;padding:8mm;background:#fff}.header{display:flex;justify-content:space-between;gap:15px;border-bottom:3px solid #312e81;padding-bottom:10px}.brand{display:flex;gap:9px;align-items:center}.logo,.logo-placeholder{width:52px;height:52px;object-fit:contain;border-radius:7px}.logo-placeholder{display:flex;align-items:center;justify-content:center;background:#312e81;color:#fff;font-size:17px;font-weight:900}h1{margin:0;font-size:17px;color:#312e81}.subtitle{font-size:7px;letter-spacing:1.3px;color:#64748b;margin-top:2px}.title{text-align:right}.title h2{margin:0;font-size:19px;color:#1e1b4b}.meta{margin-top:4px;line-height:1.55}.grid2{display:grid;grid-template-columns:1fr 1fr;border:1px solid #dbe3ef;margin-top:9px}.box{padding:8px;min-height:92px}.box+.box{border-left:1px solid #dbe3ef}.label{font-size:6.5px;font-weight:900;letter-spacing:1px;color:#6366f1;margin-bottom:4px}.name{font-size:11px;font-weight:900}.line{margin-top:3px;line-height:1.35}.info{display:grid;grid-template-columns:repeat(3,1fr);border:1px solid #dbe3ef;margin-top:7px}.cell{padding:6px}.cell+.cell{border-left:1px solid #dbe3ef}.cell small{display:block;color:#64748b;font-size:6.5px;text-transform:uppercase;font-weight:800;margin-bottom:2px}table{width:100%;border-collapse:collapse;margin-top:9px}th{background:#1e1b4b;color:#fff;padding:5px;text-align:left;font-size:6.5px}td{padding:5px;border-bottom:1px solid #e2e8f0}tr:nth-child(even){background:#f8fafc}.r{text-align:right}.b{font-weight:900}.bottom{display:grid;grid-template-columns:1fr 190px;gap:9px;margin-top:9px}.section,.summary{border:1px solid #dbe3ef;padding:8px}.notes{min-height:88px;line-height:1.5;white-space:pre-line}.sumrow{display:flex;justify-content:space-between;padding:5px 0;border-bottom:1px solid #edf2f7}.grand{display:flex;justify-content:space-between;background:#312e81;color:#fff;margin:7px -8px -8px;padding:8px;font-size:10px;font-weight:900}.payment{display:flex;justify-content:space-between;gap:10px;margin-top:9px;min-height:75px}.payment>div:first-child{line-height:1.5}.muted{color:#64748b;margin-top:4px}.qrwrap{text-align:center}.qr{width:72px;height:72px;object-fit:contain}.qrtext{font-size:6.5px;font-weight:800;margin-top:2px}.sign{text-align:right;margin-top:22px;min-height:42px}.sig{max-width:120px;max-height:38px;object-fit:contain;margin-left:auto;display:block}.footer{border-top:1px solid #dbe3ef;margin-top:12px;padding-top:5px;text-align:center;color:#94a3b8;font-size:6.5px}
</style></head><body><div class="page"><div class="header"><div class="brand">${d.logo?`<img class="logo" src="${d.logo}">`:`<div class="logo-placeholder">GB</div>`}<div><h1>${safe(d.seller.name,"YOUR BUSINESS")}</h1><div class="subtitle">GST INVOICE</div></div></div><div class="title"><h2>TAX INVOICE</h2><div class="meta">Invoice No: <b>${safe(d.invoiceNumber,"INV-0001")}</b><br>Invoice Date: <b>${safe(d.invoiceDate)}</b>${d.dueDate?`<br>Due Date: <b>${safe(d.dueDate)}</b>`:""}</div></div></div>
<div class="grid2"><div class="box"><div class="label">BILL FROM / SELLER</div><div class="name">${safe(d.seller.name,"Business Name")}</div><div class="line">${safe(d.seller.address)}</div><div class="line"><b>GSTIN:</b> ${safe(d.seller.gstin)}</div><div class="line"><b>State:</b> ${safe(d.seller.state)}</div><div class="line"><b>Phone:</b> ${safe(d.seller.phone)} &nbsp; <b>Email:</b> ${safe(d.seller.email)}</div></div><div class="box"><div class="label">BILL TO / BUYER</div><div class="name">${safe(d.buyer.name,"Customer Name")}</div><div class="line">${safe(d.buyer.address)}</div><div class="line"><b>GSTIN:</b> ${safe(d.buyer.gstin)}</div><div class="line"><b>State:</b> ${safe(d.buyer.state)}</div><div class="line"><b>Phone:</b> ${safe(d.buyer.phone)} &nbsp; <b>Email:</b> ${safe(d.buyer.email)}</div></div></div>
<div class="info"><div class="cell"><small>Place of Supply</small><b>${safe(d.placeOfSupply||d.buyer.state)}</b></div><div class="cell"><small>Tax Type</small><b>${r.same?"CGST + SGST":r.inter?"IGST":"GST"}</b></div><div class="cell"><small>Payment Terms</small><b>${safe(d.paymentTerms)}</b></div></div>
<table><thead><tr><th>#</th><th>Item Description</th><th>HSN/SAC</th><th class="r">Qty</th><th class="r">Rate</th><th class="r">Taxable</th><th class="r">GST</th><th class="r">Amount</th></tr></thead><tbody>${rows}</tbody></table>
<div class="bottom"><div class="section notes"><div class="label">NOTES / TERMS</div>${safe(d.notes,"Thank you for your business.")}</div><div class="summary"><div class="sumrow"><span>Taxable</span><b>${money(r.taxable)}</b></div>${r.cgst?`<div class="sumrow"><span>CGST</span><b>${money(r.cgst)}</b></div>`:""}${r.sgst?`<div class="sumrow"><span>SGST</span><b>${money(r.sgst)}</b></div>`:""}${r.igst?`<div class="sumrow"><span>IGST</span><b>${money(r.igst)}</b></div>`:""}<div class="sumrow"><span>Total GST</span><b>${money(r.totalGST)}</b></div><div class="grand"><span>GRAND TOTAL</span><span>${money(r.grand)}</span></div></div></div>${payment}
<div class="sign">${d.signature?`<img class="sig" src="${d.signature}">`:""}<b>${safe(d.signatoryName,"Authorized Signatory")}</b><div class="muted">For ${safe(d.seller.name,"Authorized Business")}</div></div>
<div class="footer">Computer-generated tax invoice. Invoice and payment information is supplied by the user. This application does not store bill data on its server.</div></div></body></html>`;
}
function showPreview(){const c=$("previewContainer");c.innerHTML="";const f=document.createElement("iframe");f.style.cssText="width:100%;height:1100px;border:0";c.appendChild(f);const d=f.contentDocument;d.open();d.write(invoiceHTML(collect()));d.close();$("previewModal").classList.remove("hidden")}
function closePreview(){$("previewModal").classList.add("hidden")}
async function downloadPDF(){
 const d=collect(),holder=document.createElement("div");holder.style.cssText="position:fixed;left:-100000px;top:0";holder.innerHTML=invoiceHTML(d).replace(/<!doctype html>[\s\S]*?<body>/i,"").replace(/<\/body><\/html>\s*$/i,"");document.body.appendChild(holder);
 try{await html2pdf().set({margin:0,filename:`${d.invoiceNumber||"GST-Invoice"}.pdf`,image:{type:"jpeg",quality:.98},html2canvas:{scale:2,useCORS:true,backgroundColor:"#fff"},jsPDF:{unit:"mm",format:"a4",orientation:"portrait"}}).from(holder.querySelector(".page")).save()}finally{holder.remove()}
}
function resetAll(){if(!confirm("Current bill clear करें?"))return;document.querySelectorAll("main input,main textarea").forEach(e=>{if(e.type!=="file")e.value=""});document.querySelectorAll("main select").forEach(e=>e.value="");state.items=[];state.nextId=1;state.logo="";state.qr="";state.signature="";["logoThumb","upiQrThumb","signatureThumb"].forEach(id=>$(id).classList.add("hidden"));["logoInput","upiQrInput","signatureInput"].forEach(id=>$(id).value="");$("invoiceDate").value=today();$("invoiceNumber").value="INV-0001";addItem();update()}
document.addEventListener("DOMContentLoaded",init);
