const e=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const s=(v,f="—")=>{v=String(v??"").trim();return v?e(v):f};const m=v=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",minimumFractionDigits:2}).format(Number(v)||0);
export function buildInvoiceHTML({invoiceNumber="",invoiceDate="",placeOfSupply="",seller={},buyer={},items=[],result={},notes="",company={}}={}){
 const rows=items.length?items.map((x,i)=>`<tr><td>${i+1}</td><td><b>${s(x.name,"Product / Service")}</b></td><td>${s(x.hsn)}</td><td>${x.qty||0}</td><td>${m(x.rate)}</td><td>${m(x.taxableAmount)}</td><td>${Number(x.gst||0)}%</td><td><b>${m(x.total)}</b></td></tr>`).join(""):`<tr><td colspan="8">No items added.</td></tr>`;
 const pay=(company.upiId||company.accountNumber||company.bankName||company.qrUrl)?`<div class="pay"><div><b>Payment Details</b>${company.upiId?`<p>UPI ID: ${s(company.upiId)}</p>`:""}${company.accountHolder?`<p>Account Holder: ${s(company.accountHolder)}</p>`:""}${company.bankName?`<p>Bank: ${s(company.bankName)}</p>`:""}${company.accountNumber?`<p>Account No: ${s(company.accountNumber)}</p>`:""}${company.ifsc?`<p>IFSC: ${s(company.ifsc)}</p>`:""}${company.branch?`<p>Branch: ${s(company.branch)}</p>`:""}${company.paymentNotes?`<p>${s(company.paymentNotes)}</p>`:""}</div>${company.qrUrl?`<img src="${e(company.qrUrl)}" class="qr" alt="UPI QR">`:""}</div>`:"";
 return `<!doctype html><html><head><meta charset="utf-8"><style>
 *{box-sizing:border-box}body{margin:0;background:#eef2f7;font:12px Arial;color:#172033}.page{width:794px;min-height:1123px;margin:auto;background:white;padding:38px}.head{display:flex;justify-content:space-between;border-bottom:3px solid #312e81;padding-bottom:20px}.identity{display:flex;gap:12px;align-items:center}.logo{width:70px;height:70px;object-fit:contain}.brand{font-size:23px;font-weight:900;color:#312e81}.title{text-align:right}.title b{font-size:25px}.box{border:1px solid #dbe3ef;margin-top:20px;padding:15px}.parties{display:grid;grid-template-columns:1fr 1fr;padding:0}.party{min-height:130px}.party+ .party{border-left:1px solid #dbe3ef;padding-left:15px}.label{font-size:9px;color:#6366f1;font-weight:900;text-transform:uppercase;margin-bottom:8px}.name{font-size:15px;font-weight:900}.meta{display:grid;grid-template-columns:repeat(3,1fr);padding:0}.meta>div{padding:11px}.meta>div+div{border-left:1px solid #dbe3ef}table{width:100%;border-collapse:collapse;margin-top:20px}th{background:#1e1b4b;color:white;padding:9px;font-size:9px}td{padding:9px;border-bottom:1px solid #e2e8f0}th:nth-child(2){width:25%}.bottom{display:grid;grid-template-columns:1fr 280px;gap:20px;margin-top:20px}.sum{border:1px solid #dbe3ef}.sum div{display:flex;justify-content:space-between;padding:9px 12px;border-bottom:1px solid #edf2f7}.total{background:#312e81;color:white;font-size:15px;font-weight:900}.pay{border:1px solid #dbe3ef;margin-top:20px;padding:14px;display:flex;justify-content:space-between}.pay p{margin:5px 0}.qr{width:100px;height:100px;object-fit:contain}.sign{text-align:right;margin-top:45px}.foot{text-align:center;color:#94a3b8;border-top:1px solid #dbe3ef;margin-top:30px;padding-top:10px;font-size:9px}</style></head><body><div class="page">
 <div class="head"><div class="identity">${company.logoUrl?`<img class="logo" src="${e(company.logoUrl)}">`:""}<div><div class="brand">${s(company.name||seller.name,"YOUR BUSINESS")}</div><div>GST BILL MAKER</div></div></div><div class="title"><b>TAX INVOICE</b><div>Invoice No: <b>${s(invoiceNumber,"INV-0001")}</b><br>Invoice Date: <b>${s(invoiceDate)}</b></div></div></div>
 <div class="box parties"><div class="party"><div class="label">Bill From / Seller</div><div class="name">${s(seller.name,"Not Provided")}</div><p>${s(seller.address,"Address not provided")}</p><p>GSTIN: <b>${s(seller.gstin)}</b><br>State: <b>${s(seller.state)}</b></p></div><div class="party"><div class="label">Bill To / Buyer</div><div class="name">${s(buyer.name,"Not Provided")}</div><p>${s(buyer.address,"Address not provided")}</p><p>GSTIN: <b>${s(buyer.gstin)}</b><br>State: <b>${s(buyer.state)}</b></p></div></div>
 <div class="box meta"><div><b>Place of Supply</b><br>${s(placeOfSupply||buyer.state)}</div><div><b>Tax Type</b><br>${result.isSameState?"CGST + SGST":result.isInterState?"IGST":"GST"}</div><div><b>Currency</b><br>Indian Rupee (INR)</div></div>
 <table><thead><tr><th>#</th><th>Item</th><th>HSN/SAC</th><th>Qty</th><th>Rate</th><th>Taxable</th><th>GST</th><th>Amount</th></tr></thead><tbody>${rows}</tbody></table>
 <div class="bottom"><div class="box"><div class="label">Notes / Terms</div><p>${s(notes,"Thank you for your business.")}</p></div><div class="sum"><div>Taxable <b>${m(result.taxableAmount)}</b></div>${result.cgst?`<div>CGST <b>${m(result.cgst)}</b></div>`:""}${result.sgst?`<div>SGST <b>${m(result.sgst)}</b></div>`:""}${result.igst?`<div>IGST <b>${m(result.igst)}</b></div>`:""}<div>Total GST <b>${m(result.totalGST)}</b></div><div class="total">Grand Total <b>${m(result.grandTotal)}</b></div></div></div>
 ${pay}<div class="sign">____________________<br><b>Authorized Signatory</b><br>For ${s(company.name||seller.name)}</div><div class="foot">Computer-generated tax invoice.</div></div></body></html>`}
export function renderInvoicePreview(c,data){c.innerHTML="";const f=document.createElement("iframe");f.style.cssText="width:100%;height:900px;border:0";c.appendChild(f);const d=f.contentDocument;d.open();d.write(buildInvoiceHTML(data));d.close();}
